name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        # WICHTIG: --base-href ist nötig, damit GitHub Pages die Pfade findet
        run: npx ng build --configuration production --base-href /angular-initial-pwa/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Hier wieder dein verifizierter Pfad
          path: dist/angular-initial-pwa/browser

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
